### PR TITLE
remove old ChangeLog

### PR DESCRIPTION
**Pull request by mariuz**
remove old ChangeLog

### CODE REVIEW

**Comment by mrotteveel** [comment]
I see no problems with removing this. @paulvink What do you think?

**Comment by paulvink** [comment]
> I see no problems with removing this. @paulvink What do you think?

It's horribly outdated and nobody will miss it. But does removing also wipe out its history?

**Comment by mariuz** [comment]
@paulvink 
History remains here is the example with my fork

https://github.com/mariuz/firebird-documentation/commits/0677887ed9cdfc66d909aa46d75c3b42c765bf82/ChangeLog

**Comment by paulvink** [comment]
> History remains here is the example with my fork

Thanks @Mariuz, then by all means let's remove it.

**Pull request merged**
