### PR TITLE
Missing hex-string literal + SQL conformance of date/timestamp literal

### PR DESCRIPTION
**Pull request by mrotteveel**
Adds example of missing binary string literal, and changes example date format to the YYYY-MM-DD format that is specified in the SQL standard.

### CODE REVIEW

**Comment by helebor** [comment]
Mark, I see you have been popping in corrections to docs, Fine, but you need to attend to a couple of things when you do so.
1) Update the the (bookname).xml file in the directory where the chapter files are.  This means pushing up the rightmost version element and the date.
2) When you enter the obligatory comment, make the first word the name of the book and the second word the name of the chapter before adding the summary of the change(s), e.g., fblangref25.commons; fblangref25.structure for your latest pull requests.

**Comment by helebor** [comment]
And p.s., could you attend to the update of the book file a.s.a.p. as I want to commit the release notes 2.5.8. files and I don't want to be bumping into these awkward conflicts.

**Comment by mrotteveel** [comment]
@helebor For your first point, I considered think these changes so minor, it wouldn't need to bump the version of the document. I will update it.

Maintaining a version and 'last update' this way, creates a chokepoint for multiple pull requests (by the same or different contributors), as this introduces a guaranteed merge conflict on each pull request to the same manual, even if they change different chapters.

For your second point, do you mean you want the git commit message to be prefixed by the affected chapters, or just the title of this pull request? If the commit message, may I ask why, because this information is already a fundamental part of the commit itself (eg, can be shown using `git log --name-status` and other ways).  Also, is would that be for every commit, or just the one updating the `(bookname).xml`? I also checked the history, but previous commits don't seem to have followed that convention.

As to your second comment, you shouldn't run into any conflicts as commits to the release notes would affect other files, so there wouldn't be any merge conflicts that can't be automatically solved by git itself. But I'll try to get it sorted today. Depending on your answers to the above points, I may close both pull requests and merge them into one new one.

**Comment by helebor** [comment]
This is the very first time in more than 15 years that anyone other than PaulV or myself has contributed directly to the books.  In CVS it was a no-brainer because one got a notification for each change in the inbox, complete with diffs and line numbers.  It's great that we now have another pair of eyes on them so we'll need to figure something out, given the confused notifications we get from github.
For now, once I see you have read this, I'll enable the Merge, sync it with local W-in-P manually and figure out what we need to do on the next Pull to the local repository.  
The situation might be the same or different for publications other than the Language Ref, release notes and (when relevant) the Developer's Guide.
As to bumping the version number, this is essential, since it's the only way translators will know whether the version they are working on is in sync with the latest.  The labels in github are useless as a guide to what happened and where.

**Pull request merged**
